import { Inter } from "next/font/google";
import "./globals.css";
import ChooseCity from "@/components/ChooseCity";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black font-inter text-white overflow-x-hidden w-full">
        {children}
        <ChooseCity />
      </body>
    </html>
  );
}
